services:
  caddy:
    image: caddy/caddy:2.8.4-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  payload:
    image: ghcr.io/goldenchrysus/aikadesign-payload
    restart: unless-stopped
    build:
      context: ./payload
      target: runner

  app:
    image: ghcr.io/goldenchrysus/aikadesign-app
    restart: unless-stopped
    build:
      context: .
      target: runner

volumes:
    caddy_data:
    caddy_config:
